# Generated by Django 4.0.4 on 2022-06-07 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre_producto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre Producto')),
                ('precio_producto', models.IntegerField(verbose_name='Precio Producto')),
                ('descripcion', models.TextField(max_length=50, null=True, verbose_name='Descripcion Producto')),
                ('stock_producto', models.IntegerField(verbose_name='Stock Producto')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.marca')),
            ],
        ),
    ]
