# Generated by Django 4.0.4 on 2022-06-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(max_length=9, primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('marca_producto', models.CharField(max_length=20, verbose_name='Marca Producto')),
                ('nombre_producto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre Producto')),
                ('precio_producto', models.IntegerField(verbose_name='Precio Producto')),
                ('stock_producto', models.IntegerField(verbose_name='Stock Producto')),
            ],
        ),
    ]
